### ISSUE TITLE
weird sprite naming bug?

### ISSUE THREAD

**Issue by cedric-h** [hackclub/game-lab#12]
I think this was fixed, but I'm leaving this note here just in case it isn't.

**Comment by cedric-h** [comment]
Uploading Screen Recording 2022-01-25 at 10.58.56 AM.mov…

**Comment by cedric-h** [comment]
https://user-images.githubusercontent.com/25539554/151012388-925d0595-2c70-46bd-a5ed-8effac1d2eeb.mov

**Comment by leomcelroy** [comment]
Fixed by preventing re-render on name change.
