### ISSUE TITLE
Share/save size limit

### ISSUE THREAD

**Issue by maxwofford** [hackclub/game-lab#19]
currently, saves over airtable's 100k character limit will fail silently. this issue tracks moving to a new storage provider & making sure existing links still work

**Comment by sampoder** [comment]
would cdn be an option?

**Comment by maxwofford** [comment]
I'm currently implementing this in https://github.com/hackclub/game-lab/pull/10 by putting the save files in s3 using an AWS lambda function. If it works well we can also move things like Muse over to it!

**Comment by leomcelroy** [comment]
No longer an issue is closed with migration to S3 bucket sharing system.
